name: Bug Report
description: File a bug report
title: 'Bug: '
labels:
  - 'type: bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for the bug you
        encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: 'Current Behavior:'
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected Behavior:'
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: _version
    attributes:
      label: Version
      description: What version are you running? Look to OpenPype Tray
      options:
        - 3.18.10-nightly.2
        - 3.18.10-nightly.1
        - 3.18.9
        - 3.18.9-nightly.11
        - 3.18.9-nightly.10
        - 3.18.9-nightly.9
        - 3.18.9-nightly.8
        - 3.18.9-nightly.7
        - 3.18.9-nightly.6
        - 3.18.9-nightly.5
        - 3.18.9-nightly.4
        - 3.18.9-nightly.3
        - 3.18.9-nightly.2
        - 3.18.9-nightly.1
        - 3.18.8
        - 3.18.8-nightly.2
        - 3.18.8-nightly.1
        - 3.18.7
        - 3.18.7-nightly.5
        - 3.18.7-nightly.4
        - 3.18.7-nightly.3
        - 3.18.7-nightly.2
        - 3.18.7-nightly.1
        - 3.18.6
        - 3.18.6-nightly.2
        - 3.18.6-nightly.1
        - 3.18.5
        - 3.18.5-nightly.3
        - 3.18.5-nightly.2
        - 3.18.5-nightly.1
        - 3.18.4
        - 3.18.4-nightly.1
        - 3.18.3
        - 3.18.3-nightly.2
        - 3.18.3-nightly.1
        - 3.18.2
        - 3.18.2-nightly.6
        - 3.18.2-nightly.5
        - 3.18.2-nightly.4
        - 3.18.2-nightly.3
        - 3.18.2-nightly.2
        - 3.18.2-nightly.1
        - 3.18.1
        - 3.18.1-nightly.1
        - 3.18.0
        - 3.17.7
        - 3.17.7-nightly.7
        - 3.17.7-nightly.6
        - 3.17.7-nightly.5
        - 3.17.7-nightly.4
        - 3.17.7-nightly.3
        - 3.17.7-nightly.2
        - 3.17.7-nightly.1
        - 3.17.6
        - 3.17.6-nightly.3
        - 3.17.6-nightly.2
        - 3.17.6-nightly.1
        - 3.17.5
        - 3.17.5-nightly.3
        - 3.17.5-nightly.2
        - 3.17.5-nightly.1
        - 3.17.4
        - 3.17.4-nightly.2
        - 3.17.4-nightly.1
        - 3.17.3
        - 3.17.3-nightly.2
        - 3.17.3-nightly.1
        - 3.17.2
        - 3.17.2-nightly.4
        - 3.17.2-nightly.3
        - 3.17.2-nightly.2
        - 3.17.2-nightly.1
        - 3.17.1
        - 3.17.1-nightly.3
        - 3.17.1-nightly.2
        - 3.17.1-nightly.1
        - 3.17.0
        - 3.16.7
        - 3.16.7-nightly.2
        - 3.16.7-nightly.1
        - 3.16.6
        - 3.16.6-nightly.1
        - 3.16.5
        - 3.16.5-nightly.5
        - 3.16.5-nightly.4
        - 3.16.5-nightly.3
        - 3.16.5-nightly.2
        - 3.16.5-nightly.1
        - 3.16.4
        - 3.16.4-nightly.3
        - 3.16.4-nightly.2
        - 3.16.4-nightly.1
        - 3.16.3
        - 3.16.3-nightly.5
        - 3.16.3-nightly.4
        - 3.16.3-nightly.3
        - 3.16.3-nightly.2
        - 3.16.3-nightly.1
        - 3.16.2
        - 3.16.2-nightly.2
    validations:
      required: true
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What platform you are running OpenPype on?
      description: |
        Please specify the operating systems you are running OpenPype with.
      multiple: true
      options:
        - Windows
        - Linux / Centos
        - Linux / Ubuntu
        - Linux / RedHat
        - MacOS
  - type: textarea
    id: to-reproduce
    attributes:
      label: 'Steps To Reproduce:'
      description: Steps to reproduce the behavior.
      placeholder: |
        1. How did the configuration look like
        2. What type of action was made
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Are there any labels you wish to add?
      description: Please search labels and identify those related to your bug.
      options:
        - label: I have added the relevant labels to the bug report.
          required: true
  - type: textarea
    id: logs
    attributes:
      label: 'Relevant log output:'
      description: >-
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context:'
      description: Add any other context about the problem here.
